/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/trucker/trucker-design.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    truckercap_thick_unweld_genesis8_1: THREE.Mesh
    truckercap_thick_unweld_genesis8_2: THREE.Mesh
    truckercap_thick_unweld_genesis8_3: THREE.Mesh
    truckercap_thick_unweld_genesis8_4: THREE.Mesh
    truckercap_thick_unweld_genesis8_5: THREE.Mesh
    truckercap_thick_unweld_genesis8_6: THREE.Mesh
    truckercap_thick_unweld_genesis8_7: THREE.Mesh
    truckercap_thick_unweld_genesis8_8: THREE.Mesh
  }
  materials: {
    brim: THREE.MeshStandardMaterial
    ['Material580939.001']: THREE.MeshStandardMaterial
    ['Material580926.001']: THREE.MeshStandardMaterial
    mesh: THREE.MeshStandardMaterial
    Material3202343: THREE.MeshStandardMaterial
    Material7824471: THREE.MeshStandardMaterial
    Material20932546: THREE.MeshStandardMaterial
    front: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/trucker-design.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_1.geometry} material={materials.brim} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_2.geometry} material={materials['Material580939.001']} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_3.geometry} material={materials['Material580926.001']} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_4.geometry} material={materials.mesh} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_5.geometry} material={materials.Material3202343} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_6.geometry} material={materials.Material7824471} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_7.geometry} material={materials.Material20932546} />
      <mesh geometry={nodes.truckercap_thick_unweld_genesis8_8.geometry} material={materials.front} />
    </group>
  )
}

useGLTF.preload('/trucker-design.glb')
